### ISSUE TITLE
Setup Environmental variables so you can use github without uploading you passwords

### ISSUE THREAD

**Issue by opm4** [opm4/dental_website#2]
Keel login credentials on .env file on the server.

check out this tutorial
https://alicecampkin.medium.com/how-to-set-up-environment-variables-in-django-f3c4db78c55f

might work on the local machine, but once the website is uploaded on the server there is little chance to keep it private anymore and I need to check if the .env can be created on the server.

**Comment by comandrei** [comment]
You shouldn't rely on a file being present, rather rely on certain environment variables being populated. This is highlighted in https://12factor.net/config

Heroku offers ways to inject the parameters like so:  https://devcenter.heroku.com/articles/config-vars#using-the-heroku-dashboard

The you can retrieve them in django settings using something like 
```python
PASSWORD = os.getenv('PASSWORD', 'defaultPassword')
```
Or use something like:
https://django-environ.readthedocs.io/en/latest/

docker-compose offers a similar mechanism for local development (basically reading an env file and exporting those to environment variables)
https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers

See a working example of this here:
https://github.com/comandrei/django-polls-app/blob/master/docker-compose.yml#L12

**Comment by opm4** [comment]
Check ouț this tutorial as well.

https://simpleisbetterthancomplex.com/2015/11/26/package-of-the-week-python-decouple.html

Might be useful

**Comment by opm4** [comment]
https://dev.to/jjokah/separating-sensitive-data-from-code-using-python-decouple-5gj4

Another exemple
